### ISSUE TITLE
Going back in browser on VerifierPlus.org has inconsistent and incorrect results

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/web-verifier-plus#97]
In Mac Safari Version 16.6 (17615.3.12.11.3, 17615), I see inconsistent performance when I verify JSON, select the Privacy Policy link and go back.

The most common problem is:

1. Go to VerifierPlus.org
2. Paste JSON to verify
3. Go to the #verifyResult page with the credential verified
4. Select Privacy Policy
5. Scroll down Privacy Policy to simulate reading it
6. Select back button in Safari
7. Browser goes "back" to the top of the Privacy Policy yet shows the #verifyResult in URL
8. Go back again goes back to the empty VerifierPlus.org Home Screen

There are other variations on this where I see the Privacy Policy page multiple times and other oddities. I think I've seen a case where the pasted json retained.

Attached is a screen recording of this in action. I restarted Safari before initiating this.

https://github.com/digitalcredentials/web-verifier-plus/assets/752326/691f58dd-6119-4b15-bb10-26a08d4dc4c2

**Comment by kayaelle** [comment]
I was able to replicate clicking on the back button leads to this url: https://verifierplus.org/#verify/results but the privacy content remains. Same happens when going to Terms of Use and then clicking the back button in the browser.

@bmuramatsu - do you expect that the previously verified credential would still be available upon hitting the back button or that the paste field would be empty?

**Comment by lautom36** [comment]
[pr](https://github.com/digitalcredentials/web-verifier-plus/pull/106)

**Comment by kayaelle** [comment]
Can be tested here for now: https://web-verifier-plus-git-tl-97-digital-credentials-consortium.vercel.app/

The back button refreshes the app so it's a cleared form.

**Comment by alexfigtree** [comment]
Keeping open until after deployment

**Comment by alexfigtree** [comment]
Deployed on 3/18/24.
